### ISSUE TITLE
Remove dependencies of base<4.8

### ISSUE THREAD

**Issue by sahnib** [wdanilo/haskell-logger#12]
Cant use it with my projects as it always gives me cabal hell due to base<4.8 like dependencies present in the .cabal file!
Can it always have a lower limit but no upper limit.

**Comment by m-renaud** [comment]
Any chance of this getting resolved soon? I would like to use this library but the base<4.8 dependency is conflicting with pretty much everything else.

**Comment by wdanilo** [comment]
Definitively! I'm sorry, I've missed that issue. I'll fix it as soon as I wake up. Thanks @m-renaud for notifying me via mail about it!

**Comment by wdanilo** [comment]
Guys please test if it works - I removed the unnecessary dependencies (to be honest I don't know why they were put there. I suppose it was a fix of some package error, but there were no comment about it, so something was messed up). Anyway it just compiled with removed deps. I didn't make any tests yet, because I've got several meetings today, but Ill do it later. Write me back if something will not work as it should. By the way, we are working on a new version of the library - API will remain the same, but the types would be much nicer :)

**Comment by m-renaud** [comment]
Thanks for addressing this so quickly! Could you publish a new version to hackage?

**Comment by wdanilo** [comment]
Of course, its there! :)
